### ISSUE TITLE
Empty Directories are left behind

### ISSUE THREAD

**Issue by mrd0ll4r** [gtronset/beets-filetote#239]
This has been discussed previously in https://github.com/gtronset/beets-filetote/issues/102, but I can't reopen that issue, and this might be a regression.

I've just started using filetote recently and I'm currently hitting this.
In my case it leaves behind artwork directories.
Relevant config:
```yaml
filetote:
  print_ignored: yes
  extensions: .log .cue .pdf .sfv .nfo .m3u .m3u8
  pairing:
    enabled: true
    extensions: .lrc
  paths:
    pattern:artworkdir: $albumpath/Artwork/$old_filename
    pattern:extras: $albumpath/Extras/$old_filename
    paired_ext:.lrc: $albumpath/$medianame_new
  patterns:
    artworkdir:
      - "[aA]rtwork/"
      - "[sS]cans/"
      - "[cC]overs/"
    extras:
      - "[eE]xtras/"
```

Beets version:
```
$ beet version
beets version 2.5.1
Python version 3.10.12
plugins: albumtypes, badfiles, discogs, duplicates, fetchart, filetote, importreplace, inline, mbsync, missing, musicbrainz, replaygain
```

It does not complain during import, but directory structures like this remain:
```
$ find The\ Animals\ -\ 1965\ -\ Animal\ Tracks\ \(2013\,\ WPCR-15414\,\ JP\,\ CD\)/
The Animals - 1965 - Animal Tracks (2013, WPCR-15414, JP, CD)/
The Animals - 1965 - Animal Tracks (2013, WPCR-15414, JP, CD)/Covers
```

For example:
```
$ find Falco\ -\ 1990\ -\ Data\ De\ Groove/
Falco - 1990 - Data De Groove/
Falco - 1990 - Data De Groove/01 - Neo Nothing - Post Of All .flac
Falco - 1990 - Data De Groove/02 - Expocityvisions .flac
Falco - 1990 - Data De Groove/03 - Charisma Kommando .flac
Falco - 1990 - Data De Groove/04 - Tanja P. Nicht Cindy C. .flac
Falco - 1990 - Data De Groove/05 - Pusher .flac
Falco - 1990 - Data De Groove/06 - Data De Groove .flac
Falco - 1990 - Data De Groove/07 - Alles Im Liegen .flac
Falco - 1990 - Data De Groove/08 - U.4.2.P.1. Club Dub .flac
Falco - 1990 - Data De Groove/09 - Bar Minor 7,11 (Jeanny Dry) .flac
Falco - 1990 - Data De Groove/10 - Anaconda 'Mour .flac
Falco - 1990 - Data De Groove/Artwork
Falco - 1990 - Data De Groove/Artwork/Data De Groove - Back Tray Insert.png
Falco - 1990 - Data De Groove/Artwork/Data De Groove - Cover Back.png
Falco - 1990 - Data De Groove/Artwork/Data De Groove - Cover.png
Falco - 1990 - Data De Groove/Data De Groove.cue
Falco - 1990 - Data De Groove/Falco - Data De Groove.log
```
when imported:
```
$ beet -vv import -t Falco\ -\ 1990\ -\ Data\ De\ Groove/
...
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Parsed query: AndQuery([SubstringQuery('ext', 'log', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'cue', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([SubstringQuery('ext', 'm3u', fast=False)])
Parsed sort: NullSort()
Parsed query: AndQuery([NoneQuery('album_id', True)])
Parsed sort: NullSort()
Parsed query: AndQuery([BooleanQuery('comp', 1, fast=True)])
Parsed sort: NullSort()
Sending event: before_item_moved
Sending event: item_moved
Sending event: database_change
Sending event: database_change
Sending event: write
Sending event: after_write
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: import_task_files
Sending event: art_set
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: album_imported
Sending event: import
Sending event: cli_exit
```

this correctly moves the artwork (as can be seen in the target directory):
```
$ find Falco/Data\ de\ Groove\ \(1990\)\ \[1991\,\ CD\]\ \[American\ Sound\ Records\,\ D2-75756\]\ \[FLAC\]/ | sort
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/01 Neo Nothing - Post of All.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/02 Expocityvisions.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/03 Charisma Kommando.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/04 Tanja P. Nicht Cindy C_.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/05 Pusher.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/06 Data de Groove.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/07 Alles im Liegen.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/08 U.4.2.P.1. Club Dub.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/09 Bar Minor 7_11 (Jeanny Dry).flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/10 Anaconda 'mour.flac
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Artwork
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Artwork/Data De Groove - Back Tray Insert.png
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Artwork/Data De Groove - Cover Back.png
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Artwork/Data De Groove - Cover.png
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Falco - Data de Groove.cue
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Falco - Data de Groove.jpg
Falco/Data de Groove (1990) [1991, CD] [American Sound Records, D2-75756] [FLAC]/Falco - Data de Groove.log
```

...but leaves behind:
```
$ find Falco\ -\ 1990\ -\ Data\ De\ Groove/ | sort
Falco - 1990 - Data De Groove/
Falco - 1990 - Data De Groove/Artwork
```

**Comment by gtronset** [comment]
@mrd0ll4r Thank you for your thorough notes and evaluation of this issue. I identified the bug and have a fix for it as part of https://github.com/gtronset/beets-filetote/pull/249. Once that is merged and the next release is available, this issue should be resolved.

**Comment by majorro** [comment]
@gtronset 
Still happens for me on 1.3.3 with beets 2.7.1

filetote config part:
```
filetote:
    extensions: .*
    print_ignored: yes

paths:
    filetote:default: $albumpath/$subpath$old_filename
```

It keeps scans subfolders
